server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/reservation/**
          filters:
            - name: CircuitBreaker
              args:
                name: reservation-service
                fallbackuri: forward:/reservationServiceFallBack
        
           
                 
  
      
         