server:
  port: 7071
  servlet:
    context-path: /reservation
spring:
  application:
    name: reservation-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: mani
    url: jdbc:mysql://localhost:3306/pip
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


